const USER_DATA = [
  { userId: "U101", name: "Alice J.", region: "North" },
  { userId: "U102", name: "Bob K.", region: "South" },
  { userId: "U103", name: "Charlie L.", region: "West" },
  { userId: "U104", name: "Dana M.", region: "North" },
];
const ORDER_DATA = [
  { orderId: "O5001", userId: "U101", date: "2025-10-25", items: 3, total: 125.50, status: "completed" },
  { orderId: "O5002", userId: "U102", date: "2025-10-25", items: 1, total: 29.99, status: "pending" },
  { orderId: "O5003", userId: "U104", date: "2025-10-26", items: 5, total: 450.00, status: "completed" },
  { orderId: "O5004", userId: "U101", date: "2025-10-26", items: 2, total: 88.00, status: "completed" },
  { orderId: "O5005", userId: "U103", date: "2025-10-27", items: 4, total: 15.99, status: "pending" },
  { orderId: "O5006", userId: "U101", date: "2025-11-01", items: 1, total: 10.00, status: "shipped" },
  { orderId: "O5007", userId: "U102", date: "2025-11-02", items: 2, total: 75.25, status: "completed" },
  { orderId: "O5008", userId: "U104", date: "2025-11-03", items: 3, total: 12.00, status: "completed" },
  { orderId: "O5009", userId: "U103", date: "2025-11-03", items: 6, total: 95.00, status: "shipped" },
  // ... Imagine 50+ more entries here ...
];

export { USER_DATA, ORDER_DATA };

// DayGoal & ConceptTaskHintsDay 1Filtering (Basic)Find all orders with
//  a status of "completed".Use .filter().
// Day 2Mapping & TransformationCreate
//   a simplified list containing only the orderId and the taxed total
//    (total * 1.10).Use .map().
// Day 3Aggregation (Basic)Calculate the total
//     revenue from all orders in the ORDER_DATA array.Use the .reduce() method
//      on the total property.
// Day 4Uniqueness & SetFind the unique list of dates
//       on which orders were placed.Use a Set on the date property.
// Day 5Data
//        Linking (Joining)Create a list of all orders, but replace the userId 
//        with the name of the user.Use a Map for fast lookup of users, then
//         loop through ORDER_DATA.
// Day 6Grouping & AggregationCalculate the
//          total number of orders placed by each user (Alice J., Bob K., etc.).
//          Use the reduce() method to build a final object where keys are names
//           and values are the count.
// Day 7Chaining & Final ReportGenerate a final
//            report: "Total revenue generated by North region orders."Filter
//             USER_DATA by region, link the IDs to ORDER_DATA, then calculate
//              the sum using .reduce().