import React from 'react';

export default function ForecastCard({ data }) {
    // 1. Destructure the CLEANED properties from the item generated by filterForecastData
    const { 
        day, 
        tempMax,    // Already a string like "18.5" (Celsius)
        tempMin,    // Already a string like "10.1" (Celsius)
        description, 
        icon 
    } = data;
    
    // 2. IMPORTANT: Remove conversion, as it was done in fetchData.
    // We only need to parse the temperature strings for rounding.
    const maxTemp = parseFloat(tempMax);
    const minTemp = parseFloat(tempMin);

    return (
        <div className="forecast-card">
            {/* 3. Use the correct CSS class name for the list item */}
            <p className="forecast-day">
                <strong>{day}</strong>
            </p>
            <img 
                src={`http://openweathermap.org/img/wn/${icon}.png`} 
                alt={description} 
                className="forecast-icon" 
            />
            
            {/* Display the weather description */}
            <p className="forecast-description">{description}</p>
            
            {/* 4. Display both Min and Max temperatures */}
            <p className="forecast-temp">
                <span className="max-temp">H: {Math.round(maxTemp)}°C</span> / 
                <span className="min-temp"> L: {Math.round(minTemp)}°C</span>
            </p>
        </div>
    );
}